### ISSUE TITLE
Interactive CLI

### ISSUE THREAD

**Issue by kevva** [kevva/brightness#1]
Should implement a interactive CLI where the user can click uparrow/downarrow to adjust the brightness.

**Comment by addyosmani** [comment]
:+1:

**Comment by ewnd9** [comment]
Hi, I made https://github.com/ewnd9/brightness-interactive-cli with inquirer for user interaction if anyone interested.

**Comment by sindresorhus** [comment]
Why make a separate module? It's better included in https://github.com/kevva/brightness-cli

**Comment by kevva** [comment]
Yup, but I'm still more interested in a bar-like solution, even though this is better than what we have today. @ewnd9, would you be interested in doing a PR instead?

**Comment by ewnd9** [comment]
Could you link some examples of bar-like solutions?

**Comment by sindresorhus** [comment]
https://www.npmjs.com/package/progress

**Comment by ewnd9** [comment]
just replaced inquirer with progress, now can be merged

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/brightness-cli/commit/6dfdf8e290ab583bd4cfe73ddd5128312beed291.
