### ISSUE TITLE
(node:8987) UnhandledPromiseRejectionWarning: Unhandled promise rejectio n (rejection id: 1): Error: No backlight device found

### ISSUE THREAD

**Issue by bharathvaj1995** [kevva/brightness#13]
This is the error that occurs when executing on linux platform.

**Comment by bharathvaj1995** [comment]
Please update the module to the latest node.js with catch()

**Comment by kevva** [comment]
> Error: No backlight device found

Using the CLI or the regular API? Anyway, you can see why it fails in the error message.

> Please update the module to the latest node.js with catch()

You should catch errors yourself.

**Comment by kevva** [comment]
Try running `ls /sys/class/backlight`. Does it list anything?

**Comment by bharathvaj1995** [comment]
Nothing. But i installed backlight using `apt-get install xbacklight `

**Comment by kevva** [comment]
What distro are you running? And I assume you can change brightness otherwise?
