### ISSUE TITLE
No effect in brightness 

### ISSUE THREAD

**Issue by hackerkid** [kevva/brightness#6]
Brightness is not changing in my Elementary OS. I am getting this as output for brightness-cli. 
`EACCES, open '/sys/class/backlight/intel_backlight/brightness'`

**Comment by kevva** [comment]
Try running it with `sudo`.

**Comment by hackerkid** [comment]
Sudo works :+1:

**Comment by kevva** [comment]
I don't know. On my Ubuntu system it works without `sudo` but as always with Linux, it might differ from distro to distro :).

**Comment by hackerkid** [comment]
Yeah. You should consider adding the need of sudo for some distros to the documentation. :)

**Comment by kevva** [comment]
Well, `EACCES` usually means there's a permission error somewhere so I'm just assuming people are aware of that.

**Comment by hackerkid** [comment]
The error is shown only in brightness-cli. It would be useful for people who are using the api.

**Comment by sindresorhus** [comment]
@kevva I would usually agree, but in this scenario it's not clear that the fix is running the command with `sudo`.

**Comment by hackerkid** [comment]
@sindresorhus I think it should be handled by the xdg-brightness module. Brightness saves the trouble of choosing the right module for corresponding os for changing brightness. :) I am newbie in node, ignore if  I am wrong.

**Comment by kevva** [comment]
Ah, good point.

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/xdg-brightness/commit/9930d1d6ee8f2be53a3abbf1f57d3591b47cc972.

**Comment by bencevans** [comment]
@kevva I'm running Ubuntu too (16.04) but require sudo have you made some modifications to your box to run without sudo?
