### ISSUE TITLE
Operating systems and computer support?

### ISSUE THREAD

**Issue by sondreb** [kevva/brightness#7]
What operating systems and computers is currently supported? Can't get it to work on Windows 10 build 10166 on a Samsung utralbook.

**Comment by kevva** [comment]
It depends on what you're trying to do. Setting brightness should work in all OS (except for some Linux distros maybe). Getting brightness doesn't work in Windows currently.

**Comment by sondreb** [comment]
I verified that it works well on the **HP Spectre 360**, setting 0.2 makes it 20%, or 0.5 makes it 50%.

On the **Samsung ATIV Book 9 Plus 13.3" QHD+**, it changes to 71% no matter what value I supply.

I will follow this issue after Windows 10 is released and perhaps the drivers and everything is updated by Samsung. I'll do another test then ;-) Thanks!

**Comment by kevva** [comment]
Interesting. Sounds like some drivers issue indeed.
